<?php

namespace JournaleBundle\Repository;

use JournaleBundle\Entity\Journale;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * JournaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function Finddql($id){
        $qb=$this->getEntityManager()
            ->createQuery("select j from JournaleBundle:Journale j where j.idchasseur=?1 ")
            ->setParameters(array(1=>$id));
        return $qb->getResult();
    }
    public function configure()
    {
        $this->setValidators(array(
            'nbchasse'    => new sfValidatorInteger(array('required' => true)), array(
                'required'   => 'Le champ message est obligatoire.',

            ))
        );
    }
    public function nbuser()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
          ->select(' COUNT(DISTINCT u.idchasseur)')
            ->from(Journale::class, 'u');
        $query = $queryBuilder->getQuery();
       return $query->getSingleScalarResult();
    }
    public function nbchasse($id)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select(' SUM(u.nbchasse)')
            ->from(Journale::class, 'u')
            ->where('u.idchasseur=?1')
            ->setParameters(array(1=>$id));
        $query = $queryBuilder->getQuery();
        return $query->getSingleScalarResult();
    }
}
